make: fix latest ndk home var

diff --git a/make-aar b/make-aar
--- a/make-aar
+++ b/make-aar
@@ -26,9 +26,9 @@ CLASSDBG="${CLASSDBG:-debug}"
 # artifact bytecode sources
 SOURCES="${SOURCES:-build/intra/tun2socks-sources.jar}"
 # android sdk/ndk versions (ANDROID_NDK_LATEST_HOME is set on github)
-LATESTNDK=${ANDROID_NDK_LATEST_HOME:-0}
+LATESTNDKHOME=${ANDROID_NDK_LATEST_HOME:-0}
 # default: stackoverflow.com/a/2013573
-NDKVER="${NDKVER:-$LATESTNDK}"
+NDKVER="${NDKVER:-0}"
 SDKVER="${SDKVER:-36}"
 
 ARG1="${1:-go}"
@@ -49,6 +49,13 @@ if [ "$NDKVER" != "0" ]; then
   ANDROID_NDK_HOME="${ANDROID_HOME}/ndk/${NDKVER}"
   ANDROID_NDK_ROOT="${ANDROID_NDK_HOME}"
   # ls will fail if NDKVER is missing, which is what we want!
+  ls -ltr $ANDROID_NDK_HOME
+  head $ANDROID_NDK_HOME/source.properties || true
+elif [ "$LATESTNDKHOME" != "0" ]; then
+  # use the latest NDK version, set by github actions
+  ANDROID_NDK_HOME="${ANDROID_NDK_LATEST_HOME}"
+  ANDROID_NDK_ROOT="${ANDROID_NDK_HOME}"
+  # ls will fail if ANDROID_NDK_LATEST_HOME is missing, which is what we want!
   ls -ltr $ANDROID_NDK_HOME
   head $ANDROID_NDK_HOME/source.properties || true
 fi
